import { JsonObject } from 'swagger-ui-express';
import { readSwaggerFile, normalizePath } from './functions';
import { SwaggerRouteStore } from '../routeStore';

/**
 * Organizes Swagger document paths into tags based on the first segment after /api/.
 * @param {JsonObject} swaggerDocument The Swagger document object.
 * @returns {JsonObject} The updated swagger document with tags.
 */
export function organizeSwaggerTags(swaggerDocument: JsonObject): JsonObject {
  swaggerDocument.tags = swaggerDocument?.tags ?? [];
  const existingTagNames = new Set(swaggerDocument.tags.map((t: any) => t.name));

  for (const pathKey of Object.keys(swaggerDocument.paths)) {
    const match = pathKey.match(/^\/api\/([^\/]+)/);
    if (!match) continue;

    const tagName = match[1];

    if (!existingTagNames.has(tagName)) {
      swaggerDocument.tags.push({
        name: tagName,
        description: `${tagName.charAt(0).toUpperCase() + tagName.slice(1)} endpoints`,
      });
      existingTagNames.add(tagName);
    }

    const pathItem = swaggerDocument.paths[pathKey];
    for (const method of Object.keys(pathItem)) {
      const operation = pathItem[method];
      if (!Array.isArray(operation.tags)) {
        operation.tags = [];
      }
      if (!operation.tags.includes(tagName)) {
        operation.tags.push(tagName);
      }
    }
  }
  return swaggerDocument;
}
export async function applyCustomRouteDescriptions(fullPath: string) {
  // Read the generated swagger file.
  const swaggerDocument = await readSwaggerFile(fullPath);
  if (!swaggerDocument.paths) swaggerDocument.paths = {};

  // Create a lookup map of normalized paths from the auto-generated document.
  const autoGeneratedPaths: { [normalizedPath: string]: string } = {};
  for (const p of Object.keys(swaggerDocument.paths)) {
    autoGeneratedPaths[normalizePath(p)] = p;
  }
  //  Merge custom route data (body, description, parameters) into existing paths.
  const customRoutes = SwaggerRouteStore.getRouteList();

  for (const route of customRoutes) {
    const normalizedCustomPath = normalizePath(route.path);
    const originalPath = autoGeneratedPaths[normalizedCustomPath];

    if (originalPath) {
      // The path exists, so we can safely merge our custom data.
      const { method, description, body, parameters } = route;
      const pathItem = swaggerDocument.paths[originalPath];

      if (pathItem[method]) {
        let requestBody = undefined;
        if (body && typeof body === 'object') {
          const example: Record<string, any> = {};
          for (const key in body) {
            if (key !== 'default') example[key] = { example: body[key] };
          }
          requestBody = {
            content: {
              'application/json': {
                schema: {
                  // example: body,
                  required: Object.keys(body),
                  properties: example,
                  type: 'object',
                },
              },
            },
          };
        }
        // Merge description and requestBody
        pathItem[method].description = description?.text || pathItem[method]?.description || '';
        if (requestBody) {
          pathItem[method].requestBody = { ...pathItem[method].requestBody, ...requestBody };
        }

        // Merge parameters
        if (parameters && Array.isArray(parameters)) {
          // pathItem[method].parameters = pathItem[method]?.parameters || [];
          pathItem[method].parameters = [...pathItem[method].parameters, ...parameters];
        }
      } else {
        console.warn(
          `\x1b[33[warn]: Method '${method.toUpperCase()}' not found for path '${originalPath}' in auto-generated docs. Custom data not applied.\x1b[0m`,
        );
      }
    } else {
      // The path from custom data does not exist in the auto-generated docs.
      console.warn(
        `\x1b[33[warn]: Path '${route.path}' from custom swagger data not found in auto-generated routes. Please check your route definition.\x1b[0m`,
      );
    }
  }
  return swaggerDocument;
}
